# Generated by Django 5.1.4 on 2025-01-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='event',
        ),
    ]
