# Generated by Django 5.1.4 on 2025-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_post_like_event'),
        ('venue', '0003_remove_eventsession_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventsession',
            field=models.ManyToManyField(blank=True, null=True, to='venue.eventsession'),
        ),
    ]
