# Generated by Django 5.1.4 on 2025-01-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_eventsession'),
        ('venue', '0004_remove_eventsession_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventvenue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
