# Generated by Django 5.1.4 on 2025-01-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_eventvenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventsession',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventvenue',
        ),
    ]
