# Generated by Django 5.1.4 on 2025-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_eventsession_remove_event_eventvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='images/events'),
        ),
    ]
