# Generated by Django 5.1.4 on 2025-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_eventsession_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsession',
            name='event',
        ),
    ]
