# Generated by Django 5.1.4 on 2025-01-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_remove_eventsession_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsession',
            name='venue',
        ),
    ]
