# Generated by Django 5.1.4 on 2025-01-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_eventsession_remove_event_eventvenue'),
        ('venue', '0004_remove_eventsession_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.AddField(
            model_name='eventsession',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='venue.venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='events.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(),
        ),
    ]
